repos:
-   repo: local
    hooks:
    -   id: generate-sphinx-docs
        name: Generate Sphinx docs
        entry: poetry run sphinx-build -b html docs/source docs/build
        language: system
        exclude: poetry.lock
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^docs/source/_autosummary/.*
    -   id: end-of-file-fixer
        exclude: ^docs/source/_autosummary/.*
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=4000']
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
        exclude: ^docs/source/_autosummary/.*
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: ^tests/.*
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--ensure-newline-before-comments", "--line-length", "88"]
-   repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.0
    hooks:
    -   id: remove-print-statements
        files: torchcache/.*\.py
