default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=4000']
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: ['--fix=lf']
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
    - id: black-jupyter
      language_version: python3.10
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: ^tests/.*
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--ensure-newline-before-comments", "--line-length", "88"]
-   repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.0
    hooks:
    -   id: remove-print-statements
        files: torchcache/.*\.py
